M48
; DRILL file {KiCad 9.0.6} date 2025-11-19T14:38:29-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-19T14:38:29-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C1.100
%
G90
G05
T1
X76.025Y-87.075
X86.185Y-87.075
T2
X66.145Y-87.075
X68.685Y-87.075
T3
X66.0Y-56.75
X66.0Y-77.5
T4
X79.185Y-57.075
X79.185Y-61.575
X85.685Y-57.075
X85.685Y-61.575
M30
